name = "test"
main = "test/cloudflare.server.ts"
compatibility_date = "2023-10-30"

[[durable_objects.bindings]]
name = "WSService"
class_name = "WSService"

[[migrations]]
tag = "v1"
new_classes = ["WSService"]